server:
  port: 8083

# DB configuration
spring:
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/GYM_PROD
    username: prod_user
    password: prod_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect