server:
  port: 8082

# DB configuration
spring:
  datasource:
    url: jdbc:postgresql://staging-db-host:5432/GYM_STG
    username: stg_user
    password: stg_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Prometheus metrics
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
