server:
  port: 1234
spring:
  application:
    name: training-service

  #Database
  datasource:
    url: jdbc:h2:mem:trainings
    driver-class-name: org.h2.Driver
    username: san
    password: sansan
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

#log
logging:
  level:
    web: debug
