server:
  port: 8085
  error:
    include-message: always

spring:
  application:
    name: training-event
  activemq:
    broker-url: tcp://localhost:61616
    queue_name: gym-app-queue

  #Database
  data:
    mongodb:
      database: training_summary
      auto-index-creation: true
      host: localhost
      port: 27017

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

#Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

#log
logging:
  level:
    web: debug

