server:
  port: 8085
  error:
    include-message: always

spring:
  application:
    name: training-event

  #Database
  datasource:
    url: jdbc:h2:mem:gym-club
    username: test
    password: test
  jooq:
    sql-dialect: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

#Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

#log
logging:
  level:
    web: debug

